name: Build and Deploy Node.js App to Azure Web App - showcar-strapi-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: 'Production'  
      
    permissions:
      id-token: write #This is required for requesting the JWT
      
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D3AEF621DBAC477AA80B3CBA8F12CAC6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E798E345306B44128AA751BB1CFE7815 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7A1BF957E9C446228F4A4DF6DFFAACBF }}
          
      - name: Create ZIP file for deployment
        run: |
          zip -r app.zip .
          
      - name: Deploy to Azure Web App
        run: |
          az webapp deploy --resource-group showcar \
                           --name showcar-strapi-app \
                           --src-path app.zip \
                           --slot production

                           
